OnePageCRM/swagger

swagger.yaml
Issue:
http://youtrack.xap.ie/issue/API-513
Related feature http://youtrack.xap.ie/issue/API-507#tab=Comments
Changs:
add deal items to deals
add predefined items
add predefined item groups
=> Api 507 deal items doc

swagger.yaml
http://youtrack.xap.ie/issue/API-497
=> Notifications endpoint API

swagger.yaml
- `Deal#date`
-> Updated field description
-> Field now correctly marked as NOT read only
- `Contact#status`
-> Field now correctly marked as read only
=> API-572 Update API Docs to reflect reality

swagger.yaml
Updated swagger docs because of the changes introduced with multiple pipelines feature
P.S. Please leave a comment and set 'Reviewed by' field here http://youtrack.xap.ie/issue/CRM-15217 after review
=> Multiple pipelines API

swagger.yaml
http://youtrack.xap.ie/issue/CRM-16782
=> CRM-16782 add note about commission_percentage base

swagger.yaml
contact_id -> contact_ids - fix to real things in old/new emails
=> add emails models extensions in api | API-604

swagger.yaml
http://youtrack.xap.ie/issue/CRM-17577
=> Fixed status_id example value

swagger.yaml
http://youtrack.xap.ie/issue/API-597
=> Docs for Contacts Cascade endpoint

swagger.yaml
add reason_lost_id to deal component
=> Add reason_lost_id to deal component

swagger.yaml
This contains the changes describing the API end-points for relationships' type and relationships.
=> Api 641 add relationship api endpoints

swagger.yaml
Add managing endpoints to predefined deal items | [Deal Items] API-614
=> Add managing endpoints to predefined deal items

swagger.yaml
based on the answer from the forum https://forum.developer.onepagecrm.com/t/unable-to-delete-an-address-from-the-contact-address-list/1117
=> add info about address cleanup

swagger.yaml
Small improvement for https://forum.developer.onepagecrm.com/t/unable-to-delete-an-address-from-the-contact-address-list/1117 request
=> Improve note for address_list change

swagger.yaml
https://xap.youtrack.cloud/issue/IOS-1062
=> Pin attachments via API

swagger.yaml
Add meetings, contact meetings and companies meetings endpoints | [Activity] CRM-20214
=> Add meetings, contact meetings and companies meetings endpoints

swagger.yaml
https://xap.youtrack.cloud/issue/API-680/API-Add-a-new-field-to-the-notes-Serializer
=> Add new linked_deal_name field to the Note response output

swagger.yaml
Add type field to pipeline object | [Delivery Pipeline] CRM-23582
=> Add type field to pipeline object

swagger.yaml
https://xap.youtrack.cloud/issue/CRM-23802/API-Validate-and-fix-Swagger-documentation-errors
=> Crm 23802/api validate and fix swagger documentation errors

swagger.yaml
https://xap.youtrack.cloud/issue/CRM-23612/CF-External-ID-Update-Swagger-documentation
=> External ID and Section Divider custom field types

swagger.yaml
https://xap.youtrack.cloud/issue/SRV-265
=> Srv 265/improve swagger documentation

swagger.yaml
https://xap.youtrack.cloud/issue/API-691/CompanyMobile-Redesign-Add-Update-organization-photo
=> Company logo API update

swagger.yaml
=> delivery pipeline | CRM-23582 
